[book]
title = "Template"
author = "Kasi Srinivasan"
language = "en"
multilingual = false
src = "src"

[output.html]
git-repository-url = "https://github.com/kasisrinivasan/notebook-template/tree/main/src"
